### ISSUE TITLE
Unknown Radeon card. <= R500

### ISSUE THREAD

**Issue by johndoe71rus** [erol-y/radeontop-gui#2]
build latest git version

Device: Radeon RX 560 Series (POLARIS11, DRM 3.36.0, 5.6.17-050617-generic, LLVM 10.0.0) (0x67ff)

try to run radeontop-gui and get segfault
root# ./radeontop-gui       
Unknown Radeon card. <= R500 won't work, new cards might.
Segmentation fault

lubuntu 18.04

**Comment by johndoe71rus** [comment]
oh, I missed.  <**=** 500 
any chance work with rx4XX/5XX ?
console radeontop can detect rx560

**Comment by erol-y** [comment]
Please check out v1.6.4 to prevent seg fault.
It has to support all polaris based models. if you let me know your card's device id, i can check it.

**Comment by johndoe71rus** [comment]
right now I can't see the video card identification. but i found an old log

[drm] initializing kernel modesetting (POLARIS11 0x1002:0x67FF 0x1458:0x22FF 0xCF)

I compiled a version of the program from git. how to check the number? options --help, --version don't work. No version output to console.

**Comment by erol-y** [comment]
Your card's device id is 0x67FF and it is a polaris11 variant. You can check it under menu: view -> query

**Comment by johndoe71rus** [comment]
Unfortunately, the segmentation error is all on startup. There are no windows.
Maybe my mistake, I didn't do make install. I run it in the build directory. Can you add a script to build the .deb package?

**Comment by erol-y** [comment]
Please, check out v1.6.5
you don't need to install but it requires root privileges.

**Comment by johndoe71rus** [comment]
maybe I found another undefined behavior 
https://paste.ubuntu.com/p/GXfGFvN642/
and is correct, card old than R500

now i test lubuntu 20.04

**Comment by erol-y** [comment]
There is script file in the root folder that you executed.

Please try  "radeontop-gui~$ ./radeontop-gui -r"
If you enter "radeontop-gui~$ ./radeontop-gui --help" it will dump:

> _Options:
> -r, --root			Run with root priv.
> -i, --installed		Run installed copy , instead of local.
> -x, --xhost			Deactivate xhost."_

And there is binary files in "out/bin/Release/radeontop-gui"

To execute "radeontop-gui~$ sudo ./out/bin/Release/radeontop-gui"

**Comment by johndoe71rus** [comment]
the first 2 times I ran the program as root.
I know that at the root of the git repository there is a radeontop-gui script that runs the radeontop-gui binary. By the way, it's a bad idea to have the same file name. For the script, you probably need to add .sh.
The program detects that there is no suitable video card, but it should not fail with a segmentation error.

**Comment by johndoe71rus** [comment]
finally got to the computer.
I don't know what's wrong. One hardware configuration, different operating systems. 

#define VERSION "v1.6.5-1-gaa45fe3"
lubuntu 20.04 https://paste.ubuntu.com/p/4h9gzgZCRM/
lubuntu 18.04 https://paste.ubuntu.com/p/SRGnftwY8y/
radeontop is work https://i.imgur.com/IvamRqS.png

**Comment by erol-y** [comment]
Do you have multi gpu?
I think there is a bug on multi gpu. check out v1.6.6

**Comment by johndoe71rus** [comment]
no, only one gpu.
inxi report https://paste.ubuntu.com/p/fC2BwtxWrW/

https://paste.ubuntu.com/p/hdSV568qC2/
lspci -vv https://paste.ubuntu.com/p/zNWDVFsvQq/

**Comment by erol-y** [comment]
Can you trace it in gdb? It can give an idea.

`apt install gdb`
`radeontop-gui$ make debug=1`
`gdb ./out/bin/Debug/radeontop-gui`
`(gdb) run`

**Comment by johndoe71rus** [comment]
In the next 2 weeks, I cannot test on rx560.
I can do a test on RS482M [Mobility Radeon Xpress 200]. I understand that this is not the same as the R500. 
https://paste.ubuntu.com/p/tD6Rr8VQFv/
and root https://paste.ubuntu.com/p/MtTGRY8RMQ/

**Comment by erol-y** [comment]
You have trouble with 3rd party libraries.
i suppose it is about gtk3 - wxwidgets libraries are not matched.
Please purge and re-install "libwxgtk3.0-gtk3-0v5"

R500 is architecture name. 
[wiki](https://en.wikipedia.org/wiki/Radeon_X1000_series)
